### ISSUE TITLE
Feature Request:  Permit access based on individual email addresses

### ISSUE THREAD

**Issue by tezmar** [thomseddon/traefik-forward-auth#1]
Would it be possible to add the ability to control access based on individual emails instead of only email domains?  for example I'd like to be able to limit access to just testuser@gmail.com.

**Comment by thomseddon** [comment]
This seems to make sense (there's a similar feature in [cloudflare/nginx-google-oauth](https://github.com/cloudflare/nginx-google-oauth)), I'm working on #3 first but would be happy to look at this

**Comment by thomseddon** [comment]
#4 has been merged and this is now supported!
