### ISSUE TITLE
Can we use DOMAIN and WHITELIST together?

### ISSUE THREAD

**Issue by altano** [thomseddon/traefik-forward-auth#102]
Feature Request: if both DOMAIN and WHITELIST are both specified, make it so that a user can pass EITHER to be authorized. I don't think anything else makes sense  b/c if you have both set, that is the only possible way you would want the DOMAIN list to be used. I think.

Thanks for the great service btw!

**Comment by thomseddon** [comment]
It's a fair point actually, as you say if people do set both then that is probably the only expected result!

Unfortunately that would be a breaking change, so would need a major version bump - but I think it probably makes sense, perhaps we could add a flag to enable that behaviour in v2 but make that the default in v3

**Comment by altano** [comment]
> Unfortunately that would be a breaking change, so would need a major version bump - but I think it probably makes sense, perhaps we could add a flag to enable that behaviour in v2 but make that the default in v3

That sounds reasonable and would be most appreciated!

**Comment by tekand** [comment]
+1 for this change. I would root for the 2.2 + flag version. Would volunteer for beta testing. :)
Thank you for all your efforts.

**Comment by thomseddon** [comment]
Merged in #106 pending release in 2.2
