### ISSUE TITLE
how to sign out?

### ISSUE THREAD

**Issue by joedefen** [thomseddon/traefik-forward-auth#105]
_Thanks; great project and very useful._  I'd very much like to provide a "button" to log the user out of my site as in  [Sign out a User](https://developers.google.com/identity/sign-in/web/sign-in#sign_out_a_user). Please advise how to sign out if there exists a way.  If not perhaps add a URL (e.g., "oauth.domain.com/_signout") if feasible?

**Comment by thomseddon** [comment]
I think this makes sense and would be useful, it just needs another endpoint (`/_oauth/signout`?) that removes the cookie.

The only reason this might not be backwards compatible would be if someone is already using that path, but given it's prefixed with the `/_oauth` path which can be explicitly configured, I think it's reasonable to assume that `/_oauth*` is reserved for this application and that if `/_oauth/signout` has been implemented, it would only be to do this anyway - as such I think this is safe for a minor version bump, but depending on how soon 3.0 is ready, I might just hold it for that anyway.

**Comment by joedefen** [comment]
Thanks! I'll keep alert for an update with the "Sign Out" feature which will be much appreciated.

**Comment by westwin** [comment]
just remove the cookie is not secure enough. As user can save the cookie and perform a successful curl request with the cookie even after you logout the cookie itself.

A more securer logout is to revoke the session on server side, which means a session storage is needed.

**Comment by thomseddon** [comment]
@westwin very true - this project provides only stateless authentication, so in this mode it wouldn't be possible to store that invalidation. There are a couple of more advanced features, such as this, that would benefit from storing some state, so it's something I'm looking at. For now, I will document this constraint so it's clear.

@joedefen I have pushed an implementation in #107 - it just needs some extra documentation 👍

**Comment by thomseddon** [comment]
Merged in #107 pending release in 2.2
