### ISSUE TITLE
Any support for RaspberryPi (Arm32v7)

### ISSUE THREAD

**Issue by GuyKh** [thomseddon/traefik-forward-auth#109]
Getting `standard_init_linux.go:211: exec user process caused "exec format error"` - when running on Raspberry Pi 3b+.

That's probably means that the project is compiled for 64 bit and i'm using 32bit.
Any workaround to make it work?

**Comment by SuperSandro2000** [comment]
Build the Docker Image on your RPi 3b+.

**Comment by veverkap** [comment]
I did that on my Pi cluster and it worked great. I can share the image if anyone needs it.

**Comment by GuyKh** [comment]
@veverkap I'd love that

**Comment by veverkap** [comment]
@GuyKh https://hub.docker.com/r/veverkap/traefik-forward-auth

**Comment by GuyKh** [comment]
@veverkap - Awesome! works like a charm. Thanks

Nevertheless - I'd love to have Arm builds coming in the major docker hub

**Comment by thomseddon** [comment]
We have #38 still open - there doesn't currently seem to be an easy way to get these onto docker hub without building and pushing them yourself 😢 

I'm glad you got this sorted, I will keep #38 open and hopefully docker hub will improve support for this in the future

**Comment by GuyKh** [comment]
@veverkap 
Apparently - there's an existing tag which works:
`thomseddon/traefik-forward-auth:2.1-arm`

**Comment by veverkap** [comment]
Yep, that seems to work for me too!  Never mind my build :)

**Comment by aymanbagabas** [comment]
I've noticed that all the ARM builds have a `linux/amd64` OS/ARCH, is that intentional?
https://hub.docker.com/r/thomseddon/traefik-forward-auth/tags?page=1&name=arm

**Comment by SuperSandro2000** [comment]
Yeah, cause it is not changed with a command before pushing.
