### ISSUE TITLE
Question(s): Redirect URI & multi-cluster deployment

### ISSUE THREAD

**Issue by DirtyCajunRice** [thomseddon/traefik-forward-auth#110]
Multi Cluster Deployment: If i have 2 k8s clusters, would i have to deploy in both clusters and keep the secret the same? pointing to an external version of the app seems to put me in an auth loop

Redirect URI: Even with auth host set it seems to be redirecting to the original subdomain.domain.tld/_oauth as the callback. With auth host set should it not point to what i have set for AuthHost?

**Comment by thomseddon** [comment]
Generally I would recommend deploying an instance of traefik-forward-auth alongside every instance of `traefik` - so if each cluster has it's own traefik, then two instances of tfa would be best (with the same secret if they have common domains).

Auth Host mode has a few requirements to get going, there is some good documentation on that here: https://github.com/thomseddon/traefik-forward-auth#auth-host-mode

Namely, your `auth-host` should be a subdomain of your `cookie-domain`. It's also worth noting, the `auth-host` will only be used when your request is towards a subdomain of a configured `cookie-domain`. It will check these requirements prior to selecting the `auth-host` as the redirect URI to ensure the final authentication cookie will work :)

**Comment by thomseddon** [comment]
Closing, but feel free to add any follow up questions if required :)
