### ISSUE TITLE
Using multiple providers in one container

### ISSUE THREAD

**Issue by PSJMcNeill** [thomseddon/traefik-forward-auth#111]
I have successfully setup oauth using google, I was looking to add support of Microsoft too. 

Is this possible using one container?

**Comment by thomseddon** [comment]
I'm happy to say, yes!

You can configure `rules`, and one of the options is to set the `provider` for a given rule, as documented here: https://github.com/thomseddon/traefik-forward-auth#option-details

So in this case, you could configure the OIDC provider to support microsoft, and configure that provider on certain domains as follows:
```
rule.microsoft-provider.rule = Host(`one.example.com`) || Host(`another.example.com`)
rule.microsoft-provider.provider = oidc
```

I hope that works out, let me know if you have any problems!

**Comment by Aerion** [comment]
I'm reopening this to ask you if it's possible to have on the same route multiple providers available.
I would be surprised if it already exists, it would need a minimal GUI (like https://github.com/oauth2-proxy/oauth2-proxy/issues/88).
This would enable to authenticate with different providers (e.g. google & microsoft), with the user authenticating choosing which provider to use.

Is there a plan for this need, is it already supported, or do you have pointers if one were to think about implementing it? 

Let me know if I should open another issue instead.
Thanks!
