### ISSUE TITLE
Retrieve user info in the application behind traefik 

### ISSUE THREAD

**Issue by vyshkov** [thomseddon/traefik-forward-auth#121]
Is it possible to find any user information from my app after user did the login via google ?

I am just thinking about usecases of this middleware: we know that user is logged in, but we don’t know who is this exact user. What it can be used for ?

In order to find user info we need to implement other google api/oauth2 handlers but on the application side, so we redirect user to the login page again to obtain the access token and then send requests to google api to retrieve this info.

But I feel like I am doing double work, what do you think ?

**Comment by thomseddon** [comment]
Hi, traefik-forward-auth will set the currently authenticated user in the `X-Forwarded-User` header, you can retrieve this in your application by adding the `authResponseHeaders = ["X-Forwarded-User"]` option in your traefik config, for example as shown here in a middlware config: https://github.com/thomseddon/traefik-forward-auth/blob/master/examples/traefik-v2/kubernetes/advanced-single-pod/traefik/middleware.yaml

Let me know if that doesn't answer your question or if you have any follup queries :)
