### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by sconnery** [thomseddon/traefik-forward-auth#123]
Hey team,

can ip whitelisting be built in please, this would ideal for api access from external sources, due redirect errors when behind oauth and the insecurity of opening it up.
prefer oauth per container but even just per instance would be great

**Comment by thomseddon** [comment]
Hey,

You can achieve this with our "rules" config, for example you could disable auth all together with:
```
rule.1.action = allow
rule.1.rule = Host(`api.example.com`)
```

Or use the rule to check a static API key:
```
# Allow requests that being with `/api/public` and contain the `Content-Type` header with a value of `application/json`
rule.1.action = allow
rule.1.rule = PathPrefix(`/api/public`) && Headers(`X-API-Key`, `static-api-key`)
```

You can also choose to use "individual authentication", where you don't apply the middleware to the entrypoint, but instead apply it to each ingress/container. Using this you can choose to include/omit the middleware as required.

Let me know if you have any more questions!

**Comment by sconnery** [comment]
Thank you ill give this a go.

There is no ip whitelist option just to whitelist the envrio to a public ip?
