### ISSUE TITLE
Project Rename + Other Proxies Support (e.g. NGINX)

### ISSUE THREAD

**Issue by thomseddon** [thomseddon/traefik-forward-auth#124]
I like the way this project provides authentication by integrating and working alongside an existing router/proxy and not acting as a proxy itself.

Currently this project is only really designed to work with traefik, but I know a number of other popular proxies support a similar style for "forward authentication", such as nginx and envoy.

I'd like to expand the scope of this project to support other proxies, but I think we'll need to rename before we do :)

So, I'd love feedback on this concept, and any smart name ideas you'd be willing to contribute, I'd been thinking about "protection" and "zero trust" and had ideas like:

- ZipTrust
- Bubble
- BubbleAuth

But I'm not in love with any of them, I will add more ideas but would appreciate and you have too!

**Comment by SuperSandro2000** [comment]
If you discuss this topic so openly people will steal the GitHub org name and domains and will try to charge you money to get them back.

**Comment by thomseddon** [comment]
I have a name! I'll probably hold onto it for a 3.0 release :)

**Comment by lawliet89** [comment]
@thomseddon Is the plan to support other proxies like Envoy still in the plans? From what I understand, Envoy works the same way as this.
