### ISSUE TITLE
examples/traefik-v2/kubernetes/simple-separate-pod -> HTTP ERROR 500

### ISSUE THREAD

**Issue by LelandSindt** [thomseddon/traefik-forward-auth#126]
I am working to implement/test the traefik-v2 kubernetes simple-separate-pod example and am getting HTTP 500 errors.

My minimally modified implementation of the example...
https://github.com/lelandSindt/whoami

My traefik implementaiton...
https://github.com/LelandSindt/traefik-helm-chart/blob/bender_k3s/traefik/values.yaml

kubectl -namespace whoami logs traefik-forward-auth-7c6cff9757-99mgd 
```
time="2020-05-23T13:54:22Z" level=debug msg="Starting with options: {\"LogLevel\":\"trace\",\"LogFormat\":\"pretty\",\"AuthHost\":\"\",\"CookieDomains\":null,\"InsecureCookie\":true,\"CookieName\":\"_forward_auth\",\"CSRFCookieName\":\"_forward_auth_csrf\",\"DefaultAction\":\"auth\",\"DefaultProvider\":\"google\",\"Domains\":[\"sway.org\"],\"LifetimeString\":43200,\"Path\":\"/_oauth\",\"Whitelist\":null,\"Providers\":{\"Google\":{\"ClientID\":\"[REDACTED].apps.googleusercontent.com\",\"Scope\":\"https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email\",\"Prompt\":\"\",\"LoginURL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"accounts.google.com\",\"Path\":\"/o/oauth2/auth\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"TokenURL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"www.googleapis.com\",\"Path\":\"/oauth2/v3/token\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"UserURL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"www.googleapis.com\",\"Path\":\"/oauth2/v2/userinfo\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"}},\"OIDC\":{\"Config\":null,\"IssuerURL\":\"\",\"ClientID\":\"\"}},\"Rules\":{},\"Lifetime\":43200000000000,\"CookieDomainsLegacy\":null,\"CookieSecureLegacy\":\"\",\"ClientIdLegacy\":\"\",\"PromptLegacy\":\"\"}"
time="2020-05-23T13:54:22Z" level=info msg="Listening on :4181"
```

kubectl  --namespace traefik logs traefik-5b875cd454-r22st  |grep whoami
```
10.42.0.1 - - [23/May/2020:15:27:50 +0000] "GET / HTTP/1.1" 500 0 "-" "-" 14389 "whoami-whoami-f1b9824e5ba48a37bae2@kubernetescrd" "-" 24ms
```

I am not entirely sure where to go from here. Is there another debug/log level that would help me understand what is failing?

**Comment by thomseddon** [comment]
I haven't tested with the traefik helm chart, so it's possible there's something else going on there.

A few things to check:
- Does it work if you remove the traefik-forward-auth middleware from your whoami app?
- Are traefik, traefik-forward-auth and whoami all in the same namespace?

**Comment by LelandSindt** [comment]
>Does it work if you remove the traefik-forward-auth middleware from your whoami app?

Indeed it does.

>Are traefik, traefik-forward-auth and whoami all in the same namespace?

they are not, which lead me to a "eureka" moment... 
https://github.com/LelandSindt/whoami/commit/043bfc313c44f5b4809aa45a0abc967dd34cb19a

I am now getting `Error 400: redirect_uri_mismatch` from google -- but I should be able to troubleshoot that...

Thank you!

**Comment by LelandSindt** [comment]
side note, I was going to issue a PR to align the secrets names...

https://github.com/thomseddon/traefik-forward-auth/blob/8902cf8735f7388e089be263504da92b9a3a1517/examples/traefik-v2/kubernetes/simple-separate-pod/k8s-traefik-forward-auth.yml#L97

https://github.com/thomseddon/traefik-forward-auth/blob/8902cf8735f7388e089be263504da92b9a3a1517/examples/traefik-v2/kubernetes/simple-separate-pod/k8s-traefik-forward-auth.yml#L38

but I found myself in analysis paralysis... should all the examples be changed to `secrets` or `traefik-forward-auth-secrets` -- if you have a preference, let me know and I will throw together a PR.

**Comment by thomseddon** [comment]
Glad that's sorted!

Good spot on the secret name, I think `traefik-forward-auth-secrets` is probably the better choice for the examples, people can change it if they wish, but it's probably a little more obvious when getting started.
