### ISSUE TITLE
Add support for REMOTE_USER header

### ISSUE THREAD

**Issue by timhammond** [thomseddon/traefik-forward-auth#13]
Would it be possible to add an option to set a HTTP Header (REMOTE_USER as the default) with the value of the authenticated user?

**Comment by thomseddon** [comment]
This seems like a good idea, have you seen a similar header elsewhere? I'm just wondering what the best name for the header would be :)

**Comment by timhammond** [comment]
https://guacamole.apache.org/doc/gug/header-auth.html

**Comment by thomseddon** [comment]
I've just pushed a fix for this, you can find the user in the `X-Forwarded-User` header :)
