### ISSUE TITLE
Question regarding Github and OIDC

### ISSUE THREAD

**Issue by natelandau** [thomseddon/traefik-forward-auth#139]
I am relatively new to creating and managing authentication services and while this service appears to provide exactly the functionality I need, I am finding the examples to be a little lacking since they are almost entirely focused on using Google as a provider.  

So, questions:

Question 1: I am planning on using Github as my authorization provider.  I have created the Github application and the associated `Client Secret` and `Client ID`.  What I can't seem to find is the correct URL on Github for the `ODIC ISSUER URL`.  Is this simply `https://github/com/`?

Question 2:  I assume that the Callback URL that I add in the Github application should be a link to the `traefik-forward-auth` container and port, is this right? 

thanks in advance for answering these question.  Once I get this up and running I'll spend some time adding a few more examples and potentially updates to the docs to help out newer users like myself and submit a pull request.

**Comment by thomseddon** [comment]
Hi!

Unfortunately github don't currently support OpenID Connect, however I have (today!) added a patch which adds support for any provider that doesn't support OpenID Connect (#138). This needs a little more work, but is the last item pegged for v2.2 which I hope to release in the next couple of weeks.

I'll do some testing with github this week and add the setup docs to the new Provider Setup wiki page: https://github.com/thomseddon/traefik-forward-auth/wiki/Provider-Setup

I'll keep this issue open and ping you when this is ready to go.

**Comment by natelandau** [comment]
wow.  thank you for the very swift response.  I think I was thrown by the following line in the readme which references GitHub.

`Supports multiple providers including Google and OpenID Connect (supported by Azure, Github, Salesforce etc.)`

I look forward to the release of #138 and definitely let me know if there's anything I can do to help....

**Comment by thomseddon** [comment]
Yes, I erroneously thought Github supported OpenID Connect 🙈 

I've just cut the v2.2 release, which incldues the generic provider support - I've tested it with Github this afternoon and it works well (apart from the slight quirk that github won't return the users email unless it is "public"). I've documented the setup here: https://github.com/thomseddon/traefik-forward-auth/wiki/Provider-Setup#github

Let me know how it goes and please re-open or create a new issue if you have any problems!

**Comment by etho201** [comment]
I'm having issues with this, or maybe I don't fully understand the documentation? Here's what I configured as environment variables in my docker-compose.yml file:

```bash
    environment:
      - PROVIDERS_GENERIC_OAUTH_CLIENT_ID=$GITHUB_CLIENT_ID
      - PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
      - PROVIDERS_GENERIC_OAUTH_USER_URL=https://github.com/login/oauth/authorize
      - PROVIDERS_GENERIC_OAUTH_AUTH_URL=https://api.github.com/user
      - PROVIDERS_GENERIC_OAUTH_TOKEN_URL=https://github.com/login/oauth/access_token
      - SECRET=$OAUTH2_PROXY_COOKIE_SECRET
```

It seems like I have the auth_url value incorrect (I suspect I've taken the documentation too literally...), because when I try to navigate to a page that requires OAuth I only see this:

```
{
  "message": "Requires authentication",
  "documentation_url": "https://docs.github.com/rest/reference/users#get-the-authenticated-user"
}
```

**Comment by etho201** [comment]
I was very tired when I made that post, and can now easily see I mixed up my values. 

```
    environment:
      - PROVIDERS_GENERIC_OAUTH_CLIENT_ID=$GITHUB_CLIENT_ID
      - PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
      - PROVIDERS_GENERIC_OAUTH_USER_URL=https://api.github.com/user
      - PROVIDERS_GENERIC_OAUTH_AUTH_URL=https://github.com/login/oauth/authorize
      - PROVIDERS_GENERIC_OAUTH_TOKEN_URL=https://github.com/login/oauth/access_token
      - SECRET=$OAUTH2_PROXY_COOKIE_SECRET
```

Now that I have them matched up properly it appears to be working fine! :laughing:
