### ISSUE TITLE
Question: How to apply different whitelists for each container?

### ISSUE THREAD

**Issue by nhendin** [thomseddon/traefik-forward-auth#140]
Hi.  Awesome SW package, I love it and it's working great for me. I have multiple Docker containers and non-container services set up all behind an auth-host based traefik-forward-auth container (using Google as auth provider).  

My gmail address  (for example) me@gmail.com is in the "whitelist".  Is it possible to have rules based on the username?  So I could add say roommate@gmail.com to the whitelist for some containers (say media servers and such) and leave others restricted to just me (e.g. various admin interfaces that I don't want others messing with).

Could I run 2 t-f-a containers and use different auth flows, one with a whitelist of both of us and one just me?  Is there an easier way?

Thanks!

--Neil.

**Comment by thomseddon** [comment]
Hey - yes, at the moment this isn't supported but there's a couple of PRs already open to add support for this, so it's definitely pegged for v2.3

The best workaround at the moment would be to run 2 tfa containers and create 2 middlewares - fortunately tfa is pretty lightweight, so this shouldn't be too taxing :)

I'll close this one out for now, but please feel free to re-open or add any further questions

**Comment by nhendin** [comment]
Thanks!  Just to make sure I understand what is needed, I would:

- add second project on the Google Developer console for a new authhost name (e.g. `auth2.domain.com`)
- make a second traefik-forward-auth container and give it a different container name (e.g. `auth2`) set it up with
    - host rules matching the `auth2` name.
    - the client secret / secret for the new `auth2` host
    - I should still be able to keep the port number 4181 as that's per container.
    - the allow list set as needed for the user names 
    - Traefik middleware defined as before but named differently so as to have traefik-forward-auth and traefik-forward-auth2 flows set up. 
- Switch each container where I need the new flow to the new auth middleware.

So I wind up with 2 fully parallel auth hosts and such.  Am I missing anything?  

Thanks!
