### ISSUE TITLE
WebAuthn

### ISSUE THREAD

**Issue by c64bob** [thomseddon/traefik-forward-auth#143]
Would you consider adding support for [WebAuthn](https://en.wikipedia.org/wiki/WebAuthn)?

**Comment by SuperSandro2000** [comment]
I don't think this is in the scope of this project. Use an identity provider which supports WebAuthn together with tfa.

**Comment by thomseddon** [comment]
Thank you for the suggestion, this is slightly out of scope of this project at the moment as we currently leave the user registration/authentication to other services and just focus on making it easy to integrate your provider at the proxy level.

I believe quite a few people use keycloak for user reg/auth, it supports OpenID Connect so can be used with this service too :)
