### ISSUE TITLE
Feature request: whitelisting some URLs

### ISSUE THREAD

**Issue by nicoulaj** [thomseddon/traefik-forward-auth#15]
It would be nice if a simple whitelisting of some specific URLs could be done, eg `-whitelist-uri=https://foo.bar/baz`.

Use case: https://github.com/healthchecks/healthchecks, which needs an open `/ping` endpoint

**Comment by libussa** [comment]
+1 on this. Also entire services; for example it would be nice to be able to only secure private parts of a stack while leaving some services open.

**Comment by thomseddon** [comment]
Yes I like this, it actually ties in with #14 in that a "none" auth method could be used for some paths.

I'll have a look at how Traefik does this (https://docs.traefik.io/basics/#matchers) and either go for a similar approach or something much more simplified, dependant on complexity.

**Comment by elliotmoso** [comment]
I have just added a PR for whitelisting incoming IP #17 Some similar approach could be reached

**Comment by thomseddon** [comment]
Thinking about this a bit more, it would be really good to have a much more fine grained control over who can access each section - we hack this a little at the moment by running multiple instances of this service.

**Comment by thomseddon** [comment]
FYI, I'm working on this in #26 

I hope to release this in the next couple of weeks

**Comment by thomseddon** [comment]
This has been released with the v2.0.0-rc1 tag on docker hub and will be officially released shortly, documentation is here: https://github.com/thomseddon/traefik-forward-auth/tree/dev
