### ISSUE TITLE
Documentation for Microsoft Provider lists wrong option names

### ISSUE THREAD

**Issue by wzur-r3** [thomseddon/traefik-forward-auth#151]
https://github.com/thomseddon/traefik-forward-auth/wiki/Provider-Setup page has wrong config options for the Microsoft Provider.

Despite saying `oidc` prover (hm? `provider` perhaps) it lists:
* providers.oidc.issuer-url - this I guess is legit
* providers.generic-oauth.client-id - not likely
* providers.generic-oauth.client-secret - ditto

I'd love to create a PR, however I don't seem to be able to.

Waldemar

**Comment by thomseddon** [comment]
Whoops, that's a sloppy copy paste on my part, I've fixed that up now - thanks for pointing it out!
