### ISSUE TITLE
Renewing access tokens fails when running IPFS 

### ISSUE THREAD

**Issue by dalanmiller** [thomseddon/traefik-forward-auth#154]
When recreating the docker image I'm able to authenticate just fine. However, I'm assuming after the token expires, I'm being redirected back to my OAuth provider (Google) clicking on my account and then getting the `Not authorized` response.

From `traefik` I'm seeing:

```
traefik                 | time="2020-07-25T23:47:38Z" level=debug msg="Remote error http://traefik-forward-auth:4181. StatusCode: 307" middlewareType=ForwardedAuthType middlewareName=forward-auth@file
```

--- (Some more investigation) 

What's weird is that I'm running an IPFS on my docker-compose host. As soon as I shut this one service down, everything works fine. _I think_ it has something to do with my IPFS Firefox extension that is hammering traefik/traefik-forward-auth API endpoint. I have the forward-auth middleware attached to this service as I don't want to expose this to the internet.

**Comment by thomseddon** [comment]
Could you post the logs from traefik-forward-auth also?

It sounds like you may be hitting #113

**Comment by thomseddon** [comment]
I'm closing this one now, but please reopen if you have more info
