### ISSUE TITLE
Dump headers in loglevel=trace

### ISSUE THREAD

**Issue by dantebarba** [thomseddon/traefik-forward-auth#161]
For debugging purposes it would be great to also dump the incoming headers into the log when trace is enabled. Don't know if there is already an option to allow this, but I couldn't find one.

**Comment by thomseddon** [comment]
We do dump the headers we work with: https://github.com/thomseddon/traefik-forward-auth/blob/174353743876301fa42a27d9e42ec528bcf06ebb/internal/server.go#L235-L243

Could I ask what your use case us for seeing other headers?

**Comment by dantebarba** [comment]
It was for debugging an Authorization header that was not being sent by the client. After enabling debug in traefik and realizing that it does dump all the headers from the request, I now see no sense in re-logging the headers in oauth too, so I'm closing the ticket. Thanks.
