### ISSUE TITLE
Is it possible to use this component as part of Portainer OAuth authentication?

### ISSUE THREAD

**Issue by GuyKh** [thomseddon/traefik-forward-auth#175]
With Portainer 2.0 (CE), the OAuth authentication became "free".

I have a traefik service with traefik-forward-auth working and I'd want to avoid the extra login if the user is logged on to Google.

Is there any way to reuse this? Or even - how to use google directly?

Any instructions?

![image](https://user-images.githubusercontent.com/3136012/91976779-2e55b680-ed2a-11ea-9cfd-396ffd5dceab.png)

**Comment by thomseddon** [comment]
In this context, Portainer is looking for an OAuth provider, which traefik-forward-auth doesn't provide. So if you wan't to use this with Google login then I'd either suggest putting your Google creds in here or just disabling portainer auth all together and instead protecting the interface with traefik-forward-auth!

**Comment by GuyKh** [comment]
Thanks @thomseddon 
For whoever will read this -- this is a great guide:
https://www.portainer.io/documentation/how-to-add-external-authentication-for-oauth-with-auth0/

**Comment by niklasgrewe** [comment]
@GuyKh cool thanks for sharing 👍  that topic also interests me a lot. Have you maybe found another solution too? I personally prefer self-hosted solutions...

@thomseddon are you perhaps aware of solutions in this context?
