### ISSUE TITLE
looking to incorporate with plexguide

### ISSUE THREAD

**Issue by Admin9705** [thomseddon/traefik-forward-auth#19]
hey been checking out your project and will attempt to intergrate within.  my program generates it own keys and etc for the user for gdrive and tdrive authentication and sets them.  let me know what you think. apologize, only way to communicate. we use all traefik.

For traefik, the program does the domain challenge and everything with containers all launching correctly.  just using the standard authentication right now.

https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
https://plexguide.com

**Comment by thomseddon** [comment]
Brilliant! Let me know if you come accross any issues or if there's any features that would ease integration!

**Comment by Admin9705** [comment]
will do!
