### ISSUE TITLE
Header value is too long.

### ISSUE THREAD

**Issue by owendemooy** [thomseddon/traefik-forward-auth#192]
I have been experiencing an issue with HomeAssistant behind Traefik 2.3.1 with Forward Auth where I get the following error:

Got more than 8190 bytes (9112) when reading Header value is too long.

I have been using whoami to check what the headers look like and I am seeing the header includes lots of _forward_auth_csrf

`Hostname: whoami
IP: 
IP: 
RemoteAddr: 
GET / HTTP/1.1
Host: 
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.68 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-NZ,en-US;q=0.9,en-GB;q=0.8,en;q=0.7
Cookie: _forward_auth_csrf_6a79d=d6a79d2e4c9678e21613a02c0bc34950; _forward_auth_csrf_07752=007752091afc48ea378723373b4ef40b; _forward_auth_csrf_9017b=b9017b6214d6ec3392ff0f55d07b0ba3; _forward_auth_csrf_d1ff20=1ff20a47f439a1e6de81a7dc3a814b9; _forward_auth_csrf_2ab6a=d2ab6a0817af1f87bbb3309193eaadb7; _forward_auth_csrf_4ccbf=e4ccbf9f13f0b137638f48319f4cd180; _forward_auth_csrf_f1ad7a=1ad7a27500f60700179fa4b41e35304; _forward_auth_csrf_31d63=f31d6392076d24777f80eb597c56f880; _forward_auth_csrf_0330c3=0330c33d4cef4c0894c757d0e93e584e; _forward_auth_csrf_fe839=fe8395ca34f5f2edd8b6c0ee3f90dd1; _forward_auth_csrf_21060=c21060dfc3c52bd74cdb2f4cdb97696c; _forward_auth_csrf_ab024b=ab024b5309812117a8c25df0aa09aff0; _forward_auth_csrf_1d64b9=d64b98303597eaad2aa21133e3e193a; _forward_auth_csrf_d508=b1d50895ce183f54806b1b6aff61b591; _forward_auth_csrf_b902f5=b902f554a00ab9db3cc730e0da60d3e3; _forward_auth_csrf_906d3e=06d3e90eb02d436177c67cde14f7e56; _forward_auth_csrf_183f=77183fe7bbaa95e15e7c014aef890dd3; _forward_auth_csrf_863b23=863b23c74b48e4e9d957e885b59076ce; _forward_auth_csrf_a544ec=544ecca28a8ad661b8edbb5d54cd9b1; _forward_auth_csrf_7249=6b7249901569a59d8b7519457be64c8c; _forward_auth_csrf_af1267=af126718a47c1366cf9e468eea9aeccd; _forward_auth_csrf_929c74=29c74ea48df3054809d67b8f9a6f731; _forward_auth_csrf_0936=d10936a2a8a98d32e7da26a41f6250fd; _forward_auth_csrf_d6a6af=d6a6af5f698cce3815c8412c2d336dad; _forward_auth_csrf_af9925=f9925718ca26e683b3e19a18be4f0ab; _forward_auth_csrf_afae=21afaebf17549d9186b536c269bdf3f9; _forward_auth_csrf_ae8ed8=ae8ed802867f8e83c0a720925e7a5948; _forward_auth_csrf_aa7b68=a7b684d9aef7412a7cbee1988170ae5; _forward_auth_csrf_a181=1ea181a03452245c07e48adc14757bd3; _forward_auth_csrf_52462e=52462ecf32e26718fb875f2f20021b49; _forward_auth_csrf_b89493=8949307daa30eb88bdf3164c1227e5a; _forward_auth_csrf_acd0=0cacd04e36cb0733a835a5071df97845; _forward_auth_csrf_4f5ebc=4f5ebccfcdeede2bf8754aa26e75e1dc; _forward_auth_csrf_52b5d6=2b5d6ea62bb47fc8472de1993ada6de; _forward_auth_csrf_67ff=bf67ff2329c15c3d29c7fe5095004b8e; _forward_auth_csrf_f88bfe=f88bfee40872fcbea48dd35c3c289ee3; _forward_auth_csrf_1dd902=dd902351b7322a10a139f03c5f011b2; _forward_auth_csrf_4551=a845514a13b571e0f32d6eedbba68bfe; _forward_auth_csrf_f90ffd=f90ffde9e5482d81b911384f06eb2dff; _forward_auth_csrf_5a6b2b=a6b2b0a38cbb36acc663103d3d100ec; _forward_auth_csrf_f65a=aef65a16468e7a43e7e1d9753e5d0711; _forward_auth_csrf_1b18d2=1b18d2f0c533e092bedb205a33fb0321; _forward_auth_csrf_0a0665=a06657137c5b802b97a9affa2fcfb8c; _forward_auth_csrf_a880=0ea880be044d988146cd47f8aace8c24; _forward_auth_csrf_a93493=a93493280982365f9535c35a204a7f5a; _forward_auth_csrf_17e879=7e87995cddd15ad3d26b74f15476ee8; _forward_auth_csrf_b0a6=9db0a6b08fbbad180a7070be680fc412; _forward_auth_csrf_0340cb=0340cb7de730d5678c683499e6537503; _forward_auth_csrf_2d87d6=d87d67c5692623d343316218f0c38c3; _forward_auth_csrf_c744=a3c7444a0fe518e9b1bc2b33e30e7707; _forward_auth_csrf_e1624a=e1624ac7343b817a2d7bdc5a98f1ba7e; _forward_auth_csrf_e5f0ba=5f0ba31c443a82ecbfcea636fd4e6a0; _forward_auth_csrf_3eeb=023eeb5dc6901a6a95d40d13ea6ac62d; _forward_auth_csrf_180a72=180a7201f381b85cb1d831c82ad7e840; _forward_auth_csrf_8f858b=f858b3b0a7e09f89212b56ed39afb81; _forward_auth_csrf_8ec1=e48ec1648a34a6b05f6e86ad9c05e35b; _forward_auth_csrf_824447=8244471b1fb8893d8289361be09bd0e0; _forward_auth_csrf_ad07fb=d07fbf76b8d97651129a31799a8c2e8; _forward_auth_csrf_bee7=57bee79b0bf61a0ffbd573824cf7358e; _forward_auth_csrf_ca2363=ca23632466fe5d6162beba2a997265d1; _forward_auth_csrf_eda2fa=da2fae734fa8ae79d62f79ad468385b; _forward_auth_csrf_2efe=5a2efea8444c74acf2eedc949fc50e53; _forward_auth_csrf_9ba4b6=9ba4b6d07f826f41344e18b3bece6a6f; _forward_auth_csrf_49ec8e=9ec8e502c620d3b82250ea2844b5520; _forward_auth_csrf_0e6f=c70e6fd248bbf36824091470da031a9c; _forward_auth_csrf_6ed5a4=6ed5a4d1a8481234c7a0ce7e159ece6d; _forward_auth_csrf_472349=72349542e59c6f4e66dfff6e6b7bb58; _forward_auth_csrf_637a=a2637a5e4ef72367b1c812e9d6851b08; _forward_auth_csrf_49179d=49179d2e95ca9c24ae45e23f14c368b3; _forward_auth_csrf_123ad0=23ad085b02279d0a473292b662907ea; _forward_auth_csrf_e4b7=f7e4b756d4cb009b140b9c20e23709f9; _forward_auth_csrf_74f04b=74f04ba50ddba590d1b29a19a658e07c; _forward_auth_csrf_a94c74=94c74093e3028c9108b6e5a934ba821; _forward_auth_csrf_fdb6=8bfdb6ceb77e7140c4f767587ec3318b; _forward_auth_csrf_1d8495=1d84950eca569d4b7d0d1a7a42467f71; _forward_auth_csrf_f8242f=8242f66d439738eee2722ec43e96943; _forward_auth_csrf_2dc4=6d2dc400a8745f2a188a171b0ba50599; _forward_auth_csrf_424721=4247214b1db59f4d0054d43afb34bba2; _forward_auth_csrf_e8c149=8c149ca15d1de275f1b8073fa6faee8; _forward_auth_csrf_1469=e61469738225969b7fe9851b8d4fbadf; _forward_auth_csrf_1440b1=1440b1d0703759230df9718454573972; _forward_auth_csrf_bbf684=bf684ae744a568514ce97d61f8e48be; _forward_auth_csrf_6d94=6c6d9490378d7c24618ccc7059fbb566; _forward_auth_csrf_64c9c5=64c9c5848ff017c07e71aa1705e40054; _forward_auth_csrf_12c095=2c0951e0a360cf531dacb2bf85a4ff8; _forward_auth_csrf_c09f=3cc09fbf9f4256719546a9322a118e30; _forward_auth_csrf_9591fb=9591fb9690a12f77be3f0d73a337fb73; _forward_auth_csrf_8d7e0e=d7e0e3520e03564351545f920941f8b; _forward_auth_csrf_9a2f=979a2fbd991b9e34d1bb02c1b34000e1; _forward_auth_csrf_df7446=df744615123284d762eeba1506d6fde2; _forward_auth_csrf_7c5b15=c5b157db9c18250d26943540a6b89d9; _forward_auth_csrf_f4f8=77f4f87566769c0677a12999cf3b10cb; _forward_auth_csrf_2ca395=2ca395b5e46173d00ed551b7f527b3a0; _forward_auth_csrf_f4038c=4038c8b6b11f771019eebe1de2eaf66; _forward_auth_csrf_1191=511191a53b4d5752d02ebf4a93d17a52; _forward_auth_csrf_25e0a0=25e0a09b65cd76e84bac117f048dd885; _forward_auth_csrf_6375c2=375c2237c747acc4b5775df4a683fe5; _forward_auth_csrf_838f=5b838fe8dfe4ffbc80f1ae33e159c7f3; _forward_auth_csrf_3746bf=3746bfe0c814fa88dc8c92e13d1f1be8; _forward_auth_csrf_f22293=22293715e57ccdb4f15b8086dfe803b; _forward_auth_csrf_2e65=f12e655621555b98d5d3ed46e54b8e7e; _forward_auth_csrf_bdd92a=bdd92aa353383fe2a78d398e0adf689b; _forward_auth_csrf_991061=910610a708deb457be2bda099fe02c9; _forward_auth_csrf_6833=cd6833a91128486f1f18fc732d4792af; _forward_auth_csrf_b26de1=b26de1442899a5b7e7542857ff1f5e26; _forward_auth_csrf_f8d310=8d3100551ab82aff56b966e944ffe61; _forward_auth_csrf_558c=ec558cc81a93f642491e0e68f14ad3ed; _forward_auth_csrf_5ea00d=5ea00d00394981c11c4ab4ffd3c9e591; _forward_auth_csrf_b214f6=214f6eabfaee560df966c3e3e559f0a; _forward_auth_csrf_625e=07625e0ac61dc586fc9a859163f46bf7; _forward_auth_csrf_060dff=060dffe7116d04a5856eb9d6612e380a; _forward_auth_csrf_2e8871=e8871f966cde47e9388d87d91cdd52e; _forward_auth_csrf_4dd1=eb4dd1941a9db0b4545bbb8db36d07d6; _forward_auth_csrf_1cd586=1cd58645ea0d7f97aa99afc288b784e2; _forward_auth_csrf_4f3a3a=f3a3af4902832227cf1fc7060c1a43c; _forward_auth_csrf_9a28=f59a28da4401a62de198a88bff199fb6; _forward_auth_csrf_91ebf7=91ebf78ade936c945060bac9b84914b5; _forward_auth_csrf_4bd471=bd471990f1eed3590dce04553c9c26d; _forward_auth_csrf_841a=40841aeeab24e4d75fab83ba0b0a7cb6; _forward_auth_csrf_51c4d3=51c4d340d542f9f4a45712822a70285f; _forward_auth_csrf_09b0f0=9b0f0e79bdd22056a9f11d04127a42a; _forward_auth_csrf_fa8e=d0fa8e7c8e9f1124b54e4bab9d957802; _forward_auth_csrf_275eaa=275eaa67d6d2f98790b5acc4c6951027; _forward_auth_csrf_f62264=6226418b8329eb0491590858a9586ba; _forward_auth_csrf_25a8=ba25a89380fc08ed5149388c780d07e7; _forward_auth_csrf_ea1fc1=ea1fc1b3bcb75ac63b19e279bf0aa047; _forward_auth_csrf_bfa68a=fa68ae89765fb8118b24f284e9a19f6; _forward_auth_csrf_a16f=a5a16f3ade5131ec8f7ba89ab7cf64a0; _forward_auth_csrf_f39c30=f39c30e7ea58a2ba6011ed8a291377ec; _forward_auth_csrf_134600=3460060f90f24e1b4042fb42aa31734; _forward_auth_csrf_eca1=46eca161b771df7540333a6e20b63e47; _forward_auth_csrf_5694fe=5694feb17300999351a9e2fd6474d9fa; _forward_auth_csrf_d86113=86113993f0f25a20bcedc90b9f6926d; _forward_auth_csrf_2fdb=272fdbe48587b87cba9c89fb11d373ce; _forward_auth_csrf_8ea06d=8ea06de340c96299d7ee64228e606597; _forward_auth_csrf_f2eafa=2eafa57a756fdc320373251e984f418; _forward_auth_csrf_2763=dd2763ffaa962d0c0131c7166a92f679; _forward_auth_csrf_b3401f=b3401ff7f36a5d2c42f34ae3c952de2c; _forward_auth_csrf_e4364b=4364bf853da25bb826eb5e6952883ef; _forward_auth_csrf_ba0c=8bba0cdb2c0c9394b7cbbe68720c38a6; _forward_auth_csrf_569a5c=569a5cf0ab1ef31ebbbb1d566e38ede8; _forward_auth_csrf_6b3965=b39650f6bca88631a5172f44f6bc799; _forward_auth_csrf_19e6=cb19e6604fc33f0a8ba947822270bde0; _forward_auth_csrf_ea8f2d=ea8f2d9bcf14e97b7fdc743d0132c13e; _forward_auth_csrf_fa173e=a173eb5fd2e8e34176e0c92ccc39dba; _forward_auth_csrf_86bf=d586bf26232a3381fb28441e52f80292; _forward_auth_csrf_714ad8=714ad831ba8b4db824c17f7c08a3412a; _forward_auth_csrf_45f04e=5f04ea9ad0f67f934865bedfd7d9a95; _forward_auth_csrf_a78e=4aa78eeb9ebea666ef0e761f0a9c983e; _forward_auth_csrf_55470d=55470d6506c43396debf34921d35ac69; __cfduid=d6e68a3fdcdf8eb57b8c384c86c0b44ae1601795987; _forward_auth_csrf_fc33d=fc33dcc68296857742e432afc546b6d; _forward_auth_csrf_bcffe=bcffeeaee17a2482802c52322db4ae1; _forward_auth=sOkMWoo_MA5eFE_Qb4HyQ2Z95IXMM9sfgIZ94eR_MM=|1601799678|<replaced@email>
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 
X-Forwarded-Host: 
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: Traefik
X-Forwarded-User: 
X-Real-Ip: `
_I have removed some details for security reasons_

Its only HomeAssistant having issues with Header length, and interesting its one of the services I dont use the forward_auth on as it has its own auth and OTP builtin.... all other services are working fine...

I have done the following things to try and resolve this:

1. Log completely out of Google and back in - seems to fix it temporary for a week or two (but a pain to keep having to do)
2. Incognito mode - works
3. Restart services
4. Reduce lifetime from default to 1 hours 3600 - doesnt seem to fix anything as had the issue again today after a week
5. Append /_oauth/logout which does log me out but the headers still seem to retain the multiple _forward_auth cookies

I have checked the headers using whoami both with and without the _forward_auth middleware and both still seem to include the  _forward_auth_csrf

**Comment by thomseddon** [comment]
It looks like you've been trapped in an auth-loop at some point - the _forward_auth_csrf cookies should clear within an hour at most, so the fact they're still hanging around makes me think something's going wrong.

Could you post your full config?

**Comment by owendemooy** [comment]
The headers seem to be okay at the moment its been a few days and I dont seem to have a heap of _forward_auth_csrf cookies.

I did just notice I had the forward_auth middleware applied to the traefik_forward_auth container so have removed that just now but heres the rest of my config just incase I have done something else without realising:

**docker-compose:**

`
version: "3.6"
services:

  Traefik:
    container_name: Traefik
    hostname: Traefik
    image: traefik:latest
    command: 
      # Enable API
      - --api=true
      - --api.insecure=false
      - --api.dashboard=true
      - --api.debug=true
      # Enable Docker
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      # Setup EntryPoints
      #- --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --entrypoints.websecure.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22
      # Certificate Resolver
      - --certificatesResolvers.cloudflare.acme.dnschallenge=true
      - --certificatesResolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesResolvers.cloudflare.acme.dnschallenge.delayBeforeCheck=60
      - --certificatesResolvers.cloudflare.acme.email=${CF_API_EMAIL}
      - --certificatesResolvers.cloudflare.acme.storage=/etc/traefik/acme.json
      # Filer Providers
      - --providers.file.directory=/etc/traefik/config
      - --providers.file.watch=true
      # Pilot
      - --pilot.token=${TRAEFIK_PILOT_TOKEN}
      # Logging
      #- --accesslog=true
      - --log.level=INFO
    restart: always
    networks:
       IoT:
        ipv4_address: <ip address>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - ${DOCKERDIR}/traefik:/etc/traefik
      - ${DOCKERDIR}/certs:/certs
    environment:
    - TZ=${TZ}
    - CF_API_EMAIL=${CF_API_EMAIL}
    - CF_API_KEY=${CF_API_KEY}
    labels:
    # Traefik - Service
    - traefik.enable=true
    - traefik.http.services.api.loadbalancer.server.port=8080
    # Traefik - Router - HTTPS
    - traefik.http.routers.api.rule=Host(`traefik.<domain>`)
    - traefik.http.routers.api.service=api@internal
    - traefik.http.routers.api.entryPoints=websecure
    - traefik.http.routers.api.tls.certresolver=cloudflare
    - traefik.http.routers.api.middlewares=Headers@file, GoogleAuth@file




  Traefik-Forward-Auth:
    container_name: Traefik-Forward-Auth
    hostname: Traefik-Forward-Auth
    image: thomseddon/traefik-forward-auth
    restart: always    
    networks:
      IoT:
        ipv4_address: <ip address>
    environment:
    - TZ=${TZ}
    - DEFAULT_PROVIDER=google
    - PROVIDERS_GOOGLE_CLIENT_ID=${CLIENT_ID}
    - PROVIDERS_GOOGLE_CLIENT_SECRET=${CLIENT_SECRET}
    - SECRET=${SECRET}
    - INSECURE_COOKIE=false
    - COOKIE_DOMAIN=<domain>
    - LIFETIME=3600
    - AUTH_HOST=auth.<domain>
    - WHITELIST=<email>
    - LOG_LEVEL=debug
    - LOG_FORMAT=json
    labels:
    # Traefik - Service
    - traefik.enable=true
    - traefik.http.services.forwardauth.loadbalancer.server.port=4181
    # Traefik - Router - HTTPS
    - traefik.http.routers.forwardauth.rule=Host(`auth.<domain>`)
    - traefik.http.routers.forwardauth.entryPoints=websecure
    - traefik.http.routers.forwardauth.tls.certresolver=cloudflare 
    - traefik.http.routers.forwardauth.middlewares=Headers@file

  cloudflare-companion:
    container_name: Cloudflare-Companion
    hostname: Cloudflare-Companion
    image: tiredofit/traefik-cloudflare-companion:latest
    restart: always
    networks:
      IoT: 
        ipv4_address: <ip address>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TIMEZONE={$TZ}
      - TRAEFIK_VERSION=2
      - CF_EMAIL=${CF_API_EMAIL}
      - CF_TOKEN=${CF_API_KEY}
      - TARGET_DOMAIN=<domain>
      - DOMAIN1=<domain>
      - DOMAIN1_ZONE_ID=${CF_ZONE_ID}
      - DOMAIN1_PROXIED=TRUE
    #labels:
      # Add hosts specified in rules here to force cf-companion to create the CNAMEs
      # Since cf-companion creates CNAMEs based on host rules, this a workaround for non-docker/external apps
      #- "traefik.http.routers.cf-companion-rtr.rule=HostHeader(`pihole.$DOMAINNAME`) || HostHeader(`hassio.$DOMAINNAME`)"


  Whoami:
    container_name: Whoami
    hostname: whoami
    image: containous/whoami
    restart: always 
    networks:
       IoT:
        ipv4_address: <ip address>
    environment:
    - TZ=${TZ}
    labels: 
    # Traefik - Service
    - traefik.enable=true
    - traefik.http.services.whoami.loadbalancer.server.port=80
    # Traefik - Router - HTTPS
    - traefik.http.routers.whoami.rule=Host(`whoami.<domain>`)
    - traefik.http.routers.whoami.entryPoints=websecure
    - traefik.http.routers.whoami.tls.certresolver=cloudflare
    - traefik.http.routers.whoami.middlewares=Headers@file
 
#Shared Networks between containers
networks:
  IoT:
    external:
      name: <network>
`

**traefik middleware config:**
I tend to use config files for the middlewares to make them easily reusable and reduce all the labels on each container

`
[http.middlewares]
  [http.middlewares.GoogleAuth.forwardAuth]
    address = "http://<ip address>:4181"
    port = 4181
    authResponseHeaders=["X-Forwarded-User"]
`

**Comment by thomseddon** [comment]
Has the issue reoccurred? I suspect this was caused by a redirect loop during setup.

It does make me think that we should clear the CSRF cookie earlier though, I've opened #198 to track that

**Comment by owendemooy** [comment]
I have been monitoring daily now the CSRF cookies and it seems to be fine... the whoami headers are not showing lots of CSRF cookies.

_NOTE: I mentioned I removed the forward-auth middleware from the traefik-forward-auth container... of course as per the example config this is required... without it my google logins would just keep coming back to the google account page... I went back and reviewed all the documentation again to make sure everything was configured properly. Just thought I would mention it as someone else may learn from my stupidity_

**Comment by thomseddon** [comment]
Glad to hear this hasn't reoccured, please reopen if it happens again!
