### ISSUE TITLE
support for several auth-host necessary ?

### ISSUE THREAD

**Issue by toxic0berliner** [thomseddon/traefik-forward-auth#193]
Hello,

I see that you already support several values for cookie-domain, but only a single auth-host.

I have 2 main domains : example1.com and example2.io

I have this forward.ini config : 
```
cookie-domain = example1.com
cookie-domain = example2.io
auth-host = auth.example2.io
auth-host = auth.example1.com
# right now only the last auth-host is used so that's why the reverse order as you'll in my example below
```

It works quite nice, going to myservice.example1.com I do have successfull authentication with oAuth by Google with a callback url at auth.example1.com

but when I use otherservice.example2.io the oAuth fails because the redirect_uri is otherservice.example2.io/_oauth and not auth.example1.com or even auth.example2.io

I know I could fix it by allowing otherservice.example2.io/_oauth in my google console, but I'd like it to work for all my subdomains and not type them one by one...

You do already have a mechanism to disable Auth Host Mode when you see the root domain is not the same, and I don't really understand why, I suspect that you would not be able to set cookies for example2.io when the callback uri used is auth.example1.com

But maybe you could complexify this mechanism just a bit and enable me to have 2 auth-hosts and switch between them seemlessly ? I already have both auth.example1.com and auth.example2.io beeing forwarded sucessfully by traefik to this forward-auth container...

I looked for workarounds, I thought I could duplicate the container with another auth-host but I have no idea how I could direct traefik to use one or the other middleware based on the hostname... As it is, I only have 1 service declaration that responds for both domains with `Host('myservice.example1.com','myservice.example2.io')` in traefik.

Thank you in advance for your kind help,
Regards,
Toxic.

**Comment by thomseddon** [comment]
Hi, we have #115 open to track this feature request, but so I can understand your use case, why is it that you'd like to have multiple auth hosts?

The most common use case for an auth host, is when you have multiple services on a single domain, so to save adding every domain to the oauth provider, you just need to add the auth host. If you're not doing that, there isn't really any benefit to using an auth host, so you can get away with just using the default behaviour (no auth host). Do you have multiple services, on each domain?

**Comment by toxic0berliner** [comment]
Exactly as you said. I have multiple services running on several domains;) 
This auth-host allows me to not input them all on oAuth provider for one domain but without this feature I still have to input them all for the other domain.
Thanks for the feedback and inquiry!

**Comment by toxic0berliner** [comment]
Closing as it is really exactly the requirement in enhancement #115
