### ISSUE TITLE
Loading secrets from files

### ISSUE THREAD

**Issue by yuvalfri** [thomseddon/traefik-forward-auth#195]
I want to use docker-compose's integrated secrets mechanism instead pf loading them into environment variables, is this possible?

**Comment by VictorElHajj** [comment]
I have the same issue. I thought it was standard to support "_FILE" for secret env vars.

**Comment by thomseddon** [comment]
Hi - yes this can be done, it's been asked and answered a few times - here's a full explanation: https://github.com/thomseddon/traefik-forward-auth/issues/155#issuecomment-664630985

I've opened an issue to ensure this is added to the main docs 👆
