### ISSUE TITLE
Enhancement Request : Rule for IP-Whitelist or HeadersRegexp

### ISSUE THREAD

**Issue by toxic0berliner** [thomseddon/traefik-forward-auth#197]
I realy like this forward-auth middleware, it is working find for me, but I would  like to have a way to have this middleware auto-grant access for certain IPs.
I'm not the only one having this use-case and people are going through [long workarounds](https://community.traefik.io/t/traefik-v2-simple-trick-to-bypass-basic-auth/2012/3) to implement that. I quite dislike having to duplicate the routers and using priority, especially since it will not work with a docker provider for example.
So having a rule like this would be very nice : 
```
HeadersRegexp(`X-Real-Ip`, `^(192\\.168\\.99\\.2)`)
```

I'm available to help understand the use-case or even test out the new version (using docker on my side)

**Comment by thomseddon** [comment]
Hello - both Headers and HeadersRegexp are supported under the rule config, so would something like this work:

```
# Allow single IP
rule.allow-single.action = allow
rule.allow-single.rule = Headers(`X-Real-Ip`, `192.168.99.2`)

# Allow IP range
rule.allow-range.action = allow
rule.allow-range.rule = HeadersRegexp(`X-Real-Ip`, `^192\.168\.99\.[2-10]`)

# Allow subnet
rule.allow-subnet.action = allow
rule.allow-subnet.rule = HeadersRegexp(`X-Real-Ip`, `^192\.168\.99\.`)
```

**Comment by toxic0berliner** [comment]
Amazing ! This works like a charm !
Thanks a lot @thomseddon !

Would advise to add these 3 sets of rule examples in the README.md since I did not find it in the doc.

I could do a PR if you prefer, I just thought it's faster for you to add a few lines than to merge a PR on README.md, but as you prefer ! ;) Amazing work on this traefik-forward-auth ! Thanks again !
