### ISSUE TITLE
500 error after traefik upgrade (and downgrade) on oauth middlewares

### ISSUE THREAD

**Issue by brandonhowlett** [thomseddon/traefik-forward-auth#200]
Since upgrading traefik 2.2.7 to 2.3.2 I've begun receiving an HTTP error 500 on all requests that use an oauth middleware. The error has persisted since downgrading. Routers that use no-auth middleware have not been affected. I've cleared all DNS caches, cookies, etc., as well.

level=debug msg="Error calling https://oauth:4181. Cause: Get \"http://oauth:4181\": dial tcp: lookup oauth on 127.0.0.11:53: no such host" middlewareName=middlewares-oauth@file middlewareType=ForwardedAuthType

Any thoughts as to why this is occurring and persisting?

**Comment by thomseddon** [comment]
That error looks to me like an error querying your internal DNS server within your cluster - I'd suggest restarting your traefik and traefik-forward-auth containers to see if that refreshes the DNS entry.

I'm going to close this issue as I don't believe it's a problem related to this project, but please reopen if you have more information.
