### ISSUE TITLE
Healthcheck

### ISSUE THREAD

**Issue by kaysond** [thomseddon/traefik-forward-auth#209]
Would it be possible to get a healthcheck added to this? Since the container is built from scratch and its only a single executable, I can't run `wget` or `curl` to ping the listener. Might be easiest to make another simple healthcheck binary that just makes an http request and exits 1 on failure?

**Comment by thomseddon** [comment]
What's the use case for running a health check binary inside the container? Normally this would be performed by the orchestrator?

It could perhaps make sense to add a healthz style endpoint which can be polled, but the binary should exit if there's any major issue, which the orchestrator should pickup and therefore reschedule.

Moving to discussion
