### ISSUE TITLE
trying to get this going 

### ISSUE THREAD

**Issue by Admin9705** [thomseddon/traefik-forward-auth#21]
Ok, Ive changed this post quite abit.  I figured tons of things out along the way and only one thing left!

If you look at the bottom, you look below; I have the oauth which is suppose to be the auth label; but fails to works.  so if I type portainer.domain.com; I get the I need to add to the list, but if I type netdata.domain.com, it works (because it's added below).  Basically, I cannot get the auth to work to kick in for everything.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/24727006/50527258-1bdaa280-0a9c-11e9-849d-bd2861e1bbe4.png">

**FOR THE EXECUTION**
`

    - name: "Set Known Facts"
      set_fact:
        pgrole: "auth"
        image: "thomseddon/traefik-forward-auth"

    - name: "Setting PG Labels"
      set_fact:
        pg_labels:
          traefik.enable: "true"
          traefik.port: "4181"
          traefik.backend: "oauth"
          traefik.frontend.rule: "Host:oauth.domain.com"

    - name: "Setting PG ENV
      set_fact:
        pg_env:
          PUID: "1000"
          PGID: "1000"
          CLIENT_ID: "xxxx.apps.googleusercontent.com"
          CLIENT_SECRET: "xxxx"
          SECRET: test
          COOKIE-DOMAINS: domain.com
          COOKIE_SECURE: true
          AUTH_HOST: oauth.domain.com

    - name: "Deploying Container - {{pgrole}}"
      docker_container:
        name: "{{pgrole}}"
        image: "{{image}}"
        pull: "yes"
        env: "{{pg_env}}"
        restart_policy: always
        networks:
          - name: plexguide
            aliases:
              - "plexguide"
        state: started
        labels: "{{pg_labels}}"
`

FOR TOML

```
insecureskipverify = true

logLevel = "WARN"

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    MinVersion = "VersionTLS12"
    CipherSuites = ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_RSA_WITH_AES_256$
  [entryPoints.monitor]
  address = ":8081"

    [entryPoints.https.auth.forward]
    address = "http://oauth:4181"
    authResponseHeaders = ["X-Forwarded-User"]

[retry]

[acme]
acmeLogging = true
email = "my@email.com"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
  [acme.dnsChallenge]
    provider = "godaddy"
    delayBeforeCheck = 30

[[acme.domains]]
  main = "domain.com"
[[acme.domains]]
  main = "*.domain.com"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "domain.com"
watch = true
exposedbydefault = false
network = "plexguide"

```

**Comment by Admin9705** [comment]
here is what i have in the console

![image](https://user-images.githubusercontent.com/24727006/50524006-29862d00-0a88-11e9-823d-51696207eadb.png)

**Comment by Admin9705** [comment]
ok getting this now

<img width="337" alt="image" src="https://user-images.githubusercontent.com/24727006/50525120-635a3200-0a8e-11e9-9303-b6fd0b482fe7.png">

**Comment by Admin9705** [comment]
I added the whitelist stuff and same invalid email thing

**Comment by thomseddon** [comment]
Hi,

Not sure if it's a typo just here but the cookie domain setting should be: `COOKIE_DOMAIN` not `COOKIE-DOMAINS`

If you can let me know if I can improve the docs then please do :)

**Comment by Admin9705** [comment]
ah good catch.  ya the documentation is a bit rough. i don't mind helping out with some of it.  my documentation is extensive, but insanely hard to do haha, https://wiki.plexguide.com - i'll test out and let you know how it works out. once baked in, i'll make a video for how others use it; but will ensure to link this project to it.  it's really great work honestly.  later on, i'm trying to figure out how to generate a username and secret id from google if possible.  i have part of the program generating service account keys.

**Comment by Admin9705** [comment]
yep that resolved the issue. baking in now
