### ISSUE TITLE
Running Traefik Ingress Controller in HA causes timeouts in client connection to backend service

### ISSUE THREAD

**Issue by shaggykp** [thomseddon/traefik-forward-auth#214]
Our Kubernetes cluster uses the Traefik ingress controller as its entry point (using Traefik v2.3.2). The Traefik IC runs behind MetalLB and within a Linkerd service mesh.

When running multiple Traefik IC pods to provide HA, we see that we get timeouts on our HTTP and TCP client connections to our backend services. If we only have 1 instance of the Traefik IC, then all works fine. Perhaps I'm missing a configuration setting in my Traefik IC deployment but I'm at a loss as to why the we're seeing this behaviour. Any thoughts or suggestions would be appreciated.

Thanks

**Comment by thomseddon** [comment]
Closing as this sounds like an issue with [traefik](https://github.com/traefik/traefik) directly - please reopen if there's more info on how this relates to this project
