### ISSUE TITLE
Traefi-forward-auth Throwing Error - 400

### ISSUE THREAD

**Issue by Not-Qualified** [thomseddon/traefik-forward-auth#221]
Authorization Error
Error 400: invalid_request
Invalid parameter value for redirect_uri: Missing scheme: :///_oauth

![Traefik-forward-auth Error](https://user-images.githubusercontent.com/52353116/102487187-27ac3e80-4090-11eb-9cfa-69ad0bd01762.png)

**Comment by subdavis** [comment]
You've clearly put in an invalid redirect_uri to the console.  

should be something like `https://auth.myserver.com/_oauth`

Please close this issue.
