### ISSUE TITLE
Need a way to deny users with empty email addresses

### ISSUE THREAD

**Issue by pjeanjean** [thomseddon/traefik-forward-auth#223]
I had a use-case where I needed to deny access to users that didn't have an email address at all.
I did a basic implementation and could submit a PR, but it would probably be a better idea to have a support for wildcards in the domain option instead.
I could try to implement it but wanted to discuss it first.

**Comment by thomseddon** [comment]
I'm not quite sure I follow as the user will need to have been authenticated to successfully authenticate, what provider are you using? Could you provide an example of when an authenticated user might not have an email address?

**Comment by pjeanjean** [comment]
Well, my use-case is a bit specific.
The provider is a personal Keycloak instance connected to an LDAP server, and depending on its groups, an authenticated user might not have access to some resources (in which case, information like the email address is not transmitted to the client, even though the authentication was successful).

Since I'm still learning how to properly manage an authentication service, my implementation might be flawed, but to me, it looks like most OIDC clients require a non-empty email address.
And since this project already has a domain white-list check system, it seems weird that there is no way to check that an email address was passed at all.

**Comment by thomseddon** [comment]
I can't think of a reason why the client shouldn't be allowed access to the email address.

Happy to reconsider if anyone can point me towards a general example of where this might happen.
