### ISSUE TITLE
Allow using Google Groups for auth approval

### ISSUE THREAD

**Issue by zenjabba** [thomseddon/traefik-forward-auth#226]
I'm not sure if https://github.com/thomseddon/traefik-forward-auth/issues/162 is the same thing and if it is I'm sorry please close me.

Basically allowing us to put users inside a specific group and allowing only those users within the group to be returned with a valid oauth token. Currently I'm using different tld for each service and having many different accounts within different tld can get confusing for the end users.

Thanks!

**Comment by thomseddon** [comment]
Thanks - I'd also like to see this, I've dug into 162 a little more as my intention was to use that to track group support. I'll open another issue if that's doesn't fit the authors intention
