### ISSUE TITLE
How to bypass certain routes while '/' is integrated with traefik-fa, a middleware for SSO integration

### ISSUE THREAD

**Issue by RamuRChenchaiah** [thomseddon/traefik-forward-auth#229]
Traefik version: 2.1

Hi,

We want to have a landing page for the application,like '/login'.The app is integrated with traefik-fa.
But we see that this route also required to gothrough authentication.

Is there anyway to avoid this?

Thank you

**Comment by thomseddon** [comment]
Yes!

You can use the rules config to permit specific URLs, this is fully documented under the "rules" section of the README: https://github.com/thomseddon/traefik-forward-auth

In your example, this could be:

```
# Allow requests to '/login'
rule.allow-login.action = allow
rule.allow-login.rule = Path(`/login`)
```

Closing as I think that solves it, but please re-open if there's any more questions!
