### ISSUE TITLE
Got your Projected Baked into PlexGuide

### ISSUE THREAD

**Issue by Admin9705** [thomseddon/traefik-forward-auth#23]
Here is the wiki for it: https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/wiki/PG-Shield

Also i'll work a youtube video and if you click this, https://plexguide.com/news/7-7-changelog/ there are screen shots at the bottom!  Hopefully more stars come your way!  put it in the sum and looks like it jumped up 7 within 2 days.  People want to use this, so they are 99% of the time going to read the wiki. Let me know if you want to trade github links or ect, plus you can list it as a major project that utilizes your project :D

**Comment by thomseddon** [comment]
Great!

A few notes:

- You don't *need* a G Suite account, you can use the `-whitelist` parameter to allow any email
- You shouldn't need portainer (but this may link some other dependency in your project)

**Comment by Admin9705** [comment]
will do, thanks for the tips!
