### ISSUE TITLE
Rule to Bypass Auth for Internal Traffic

### ISSUE THREAD

**Issue by sklose** [thomseddon/traefik-forward-auth#231]
Hi,

is it possible to define a rule that always allows requests from 192.168.0.0/24 and performs OAuth only for other (public) IP ranges? The use case is: I want to protect my home server from being open to everyone on the internet, but while I am home I don't want to be bothered with a login screen. Also, my Plex app on my Roku stops working if I enforce OAuth for local traffic ...

Thanks,
Sebastian

**Comment by ScottRoach** [comment]
There is an example doing that here: https://github.com/thomseddon/traefik-forward-auth/issues/197

Make the following rule
```
rule.allow-subnet.action = allow
rule.allow-subnet.rule = HeadersRegexp(`X-Real-Ip`, `^192\.168\.0\.`)
```

Docs

**Comment by sklose** [comment]
Thanks, works like a charm!
