### ISSUE TITLE
Not able to set "Content-Type" header as "text/plain" in traefik-forward-auth

### ISSUE THREAD

**Issue by Mayur-Khante** [thomseddon/traefik-forward-auth#232]
Hi,
We are trying to set "Content-Type" header as "text/plain" before redirection.
For the following location
https://github.com/thomseddon/traefik-forward-auth/blob/4ffb6593d569801cf7c4571542c0ff03afcb1a0f/internal/server.go#L235

Although we are setting this header it's not reflected in the redirection call made to the server.
All of the following ways we have tried. 
```
//[1]
w.Header().Set("Content-Type", "text/plain")
//[2]
r.Header.Set("Content-Type", "text/plain")
```

Any guidance for this is appreciated.
Thanks

**Comment by thomseddon** [comment]
What's your use case?
