### ISSUE TITLE
Local development documentation or How-to guides

### ISSUE THREAD

**Issue by ikhosravi** [thomseddon/traefik-forward-auth#235]
Hello all
I'm looking into running the middleware locally on my ubuntu machine to try to build and test new features but failed in running the middleware using traefik documentation guide which is based on traefik 2.3 plugin and filesystem devplugin guide.
 @thomseddon, is there any way that you could help us run the project using traefik file provider instead of docker to test/develop new features?

just as a note, by devplugin I mean adding modulename and gopath like below (which is mentioned in traefik documentation):
```
entryPoints:
  http:
    address : ":8000"
    forwardedHeaders:
      insecure : true
api:
  dashboard : true
  insecure : true

experimental:
  devPlugin:
    goPath: /home/user/mygitroot
    moduleName: traefik-forward-auth

providers:
  file:
    filename : "traefik-rules.yaml"
```
Thanks in advance

**Comment by thomseddon** [comment]
Hi - this module is a middleware, not a plugin. I would like to explore providing it as a plugin and I'd love to see a PR that tackles that issue
