### ISSUE TITLE
redirect on logout via url parameter

### ISSUE THREAD

**Issue by dmaes** [thomseddon/traefik-forward-auth#239]
When using traefik-forward-auth for multiple different apps, the `--logout-redirect` parameter is rather useless since this would redirect all apps on completely different urls to one single url after logout. It would be nice if there was something like `/_oauth/logout?redirect=someurl` that different apps could then use with different url's.

**Comment by thomseddon** [comment]
Unfortunately that would probably leave us with an open redirect. One workaround could be to use multiple instances of traefik-forward-auth?

We could potentially provide some extra options to preconfigure redirects? What's your use case?

**Comment by dmaes** [comment]
So sorry, thought I wrote up a reply to your question.

Use case is running one instance (or a few for loadbalancing/HA) for the whole kube cluster, where all applications that need auth can use that one instance. Having to run a new instance for every app with the only difference being the logout url kinda seems like a waste of resources to me. And being able to use a parameter in the url, you don't have to reconfigure your traefik-forward-auth instance for every new app, whereas with preconfigured redirects, you probably have. But if running a new instance for every app that needs one is the only solution, then so be it.
