### ISSUE TITLE
Behaviour for unauthorised requests

### ISSUE THREAD

**Issue by lukerajah** [thomseddon/traefik-forward-auth#245]
First of all, thanks for this fantastic project! Have it working nicely already, but a couple of things I'd love to customise if possible, both related to the same issue.

I can't see from the documentation what exactly happens when authentication fails. What I would like to be able to do is the following:
- [edit - initially had a separate question here about serving custom error pages, but the issue was just that my error handler needed to be earlier in the middleware chain!]
- I have some users which are authorised only for a subset of services (and in particular, not the one on the top level domain). Ideally if they are trying to log in to the top level domain (and "failing" authentication) I would like to redirect them to the service that they *are* authorised for (i.e. from example.com to example.com/service). I thought I might be able to do this with the X-Forwarded-User header but I don't *think* this gets sent if the authentication fails...

Any help much appreciated - thanks so much!

**Comment by kaysond** [comment]
> I have some users which are authorised only for a subset of services

What are you using to implement this?

**Comment by thomseddon** [comment]
Thanks :)

Unfortunately we don't support anything other than allow or deny at the moment, so logic like this would have to be implemented at an application level. I think a redirect response _might_ be outside of the scope of this project right now but thanks for the idea and I will keep it in mind.

**Comment by lukerajah** [comment]
> > I have some users which are authorised only for a subset of services
> 
> What are you using to implement this?

You can set user whitelists for each rule that you use in traefik-forward-auth (there are some examples in the documentation [here](https://github.com/thomseddon/traefik-forward-auth#user-restriction). 

Thom, thanks for taking a look and the great work on this project!
