### ISSUE TITLE
Reloading cached Website with expired token leads to CORS errors / Cross-Origin Read Blocking

### ISSUE THREAD

**Issue by Slinky-Wrangle-Punch** [thomseddon/traefik-forward-auth#253]
My setup with TFA and Google is working just fine, when I load my website for the first time and I get the access token via the Google login workflow.

But when I reload the cached Website after the token expired, I get CORS errors / CORB warnings. The reason for this is that the cached part of the website tries to get the non-static parts. Each query is redirected to TFA. There it gets approved without user interaction, because Google is still logged in.

I guess the query is than again redirected. And the result of the query would be the correct result, but now the URL has the Google Domain as origin and it gets blocked. (If I copy&paste the blocked URL into another tab, I get the correct image for example.)

Is there a way to enforce a reload of the complete page if a new token is needed? Or is it possible to avoid the Authentication Origin in the answer to the query?

**Comment by Slinky-Wrangle-Punch** [comment]
I did some more debugging. The problem was the cache of the service worker. The queries (initiated by the serviceworker) for some assets were redirected to the login page, but the login page wasn't loaded, because it wasn't the query for the complete page. I removed the serviceworker and not it is working as expected.

**Comment by Rathna-K** [comment]
@thomseddon @Slinky-Wrangle-Punch I am still facing this issue in 2.2.0 for microsoft azure auth. is there another version I should be using? TIA

**Comment by Slinky-Wrangle-Punch** [comment]
The problem wasn’t within the traefik-forward-auth. The problem was within the application forward-auth protects. The protected application installed a service worker with caching for offline usage of the application. When the application wanted to refetch some assets it failed and no redirection of the complete page to the login page was done, because only the query was redirected to the login page. The application/service worker has to detect this and to reload the complete page. 

So if your application is maintained you could ask the devs to implement this (e.g. Mealie did this) or you have to deactivate the service worker by yourself.
