### ISSUE TITLE
How to get User Details (post successful login) in backend services

### ISSUE THREAD

**Issue by siddiqskm** [thomseddon/traefik-forward-auth#254]
Firstly, Thanks a ton for this project @thomseddon - Very useful and appreciate it !!!

I have a clarification in relation to the E2E usage and listed below are the details.
Please do review and suggest !

**Setup/Context -**
- Multiple services hosted on docker swarm
- All these services are running behind Traefik (as the reverse proxy)

Was trying to enable OAuth 2.0 (via google provider) integration with my web service and thats when I came across this project.
Following the documentation - I was able to setup Traefik Forward Auth in Auth Host Mode and I get redirected to my webservice post successful login with a CSRF token generated.

Now - I need multiple backend services to validate + get user details (associated with the CSRF token generated) in further calls.

Just wondering whats the best approach to achieve this and listed below are a few additional clarifications I have -
- Can I get the User details from CSRF token inside backend services?
- Can I generate a JWT cookie from CSRF token which can be further used in the APIs that need authentication?

**Comment by thomseddon** [comment]
You can get the user's email from the `X-Forwarded-User` header: https://github.com/thomseddon/traefik-forward-auth#forwarded-headers

There isn't currently a way to access the google access_token/refresh_token, but this has been raised in #30 and #100 and may be added in the future

**Comment by Prutheus** [comment]
I do not understand how to get this header.
I have a nginx application secured by `forward-auth` middleware. In forward auth middleware, I have enabled this forwarded header. In my URL requests against my nginx is this header not set after authorisation. How can my nginx proxied application read this header?
