### ISSUE TITLE
GitHub provider whitelist with username?

### ISSUE THREAD

**Issue by Poeschl** [thomseddon/traefik-forward-auth#256]
Would it be possible to fallback to the username in case of the GitHub OAuth? With that users could als be whitelisted and filtered by rules.

I understand that its a custom setting just for GitHub but maybe it can be also a setting for the oauth provider. 
For example `--providers.generic-oauth.user-field=login` to specify the login attribute of the User Url endpoint.

**Comment by thomseddon** [comment]
I think #159 would work for you?

Please re-open if not
