### ISSUE TITLE
Single sign out.  

### ISSUE THREAD

**Issue by rizerzero** [thomseddon/traefik-forward-auth#261]
Hi, first of all, Thankyou for this tool, 

I have an issue understanding something.

I have a setup like this  :  
`vue_app1.domain.com`
`vue_app2.domain.com`  
`sso.domain.com`  (keycloak )
And all this works perfectly with SSO, I Llogin and logout once (without Traefik forward auth) 

Now I have documentation with (Mkdocs ) pure static HTML. that I wanted to secure with traefik-forward-auth.
`docs.domain.com`  and it works for securing but not for logging out. 

The problem I have now is that if I log out from `vue_app1.domain.com` then I'm logged out from `vue_app2.domain.com` but I'm not logged out from `docs.domain.com`. 
and if I use `docs.domain.com/_oauth/logout`.  I logout from the doc but not from `vue_app1.domain.com` & `vue_app2.domain.com`

can you please tell me if it's possible log out at once while using the vuejs package to login and the forward auth for the docs?  

I noticed the cookie domain is the same for the vue apps it's `sso.domain.com` but for the docs it's `.docs.domain.com` I have set the env variable COOKIE_DOMAIN to `sso.domain.com` but this did not change anything the cookie is always for `.docs.domain.com`. 

Thank you.

**Comment by thomseddon** [comment]
I think you just need to set the cookie_domain to be `domain.com`, as per the example: https://github.com/thomseddon/traefik-forward-auth#auth-host-mode

Please re-open with with your full config if that doesn't resolve :)

**Comment by rizerzero** [comment]
Thank you, i'll open an new issue
