### ISSUE TITLE
https url-path

### ISSUE THREAD

**Issue by moreiramarti** [thomseddon/traefik-forward-auth#27]
Hello,

I'm trying you forwarder and I'm facing and issue with https.
When I call my service, let's say https://service.domain.com, I get a 400 error code saying : 
he redirect URI in the request, https://service.domain.com/_oauth, does not match the ones authorized for the OAuth client.

How can I make the url path called with https ?

Regards,
Martinho MOREIRA

**Comment by thomseddon** [comment]
Have you added https://service.domain.com/_oauth in the Google Oauth Console?

**Comment by moreiramarti** [comment]
I did but the calling url is http and not https.
Do you know why ? Maybe a missing header

**Comment by thomseddon** [comment]
Sorry I'm not following you, in your example all the URL's had https at the start, so I can't see an issue with that.

Could you give an example request flow?

**Comment by moreiramarti** [comment]
Sure, I'm call my service with https then I'm redirected to google auth screen but I get a 400 error with the message : the redirect URI in the request, http://service.domain.com/_oauth, does not match the ones authorized for the OAuth client.

I did a wrong copy paste in my initial post. The _oauth url is called with http instead of https.

**Comment by thomseddon** [comment]
Hmm, are you sure your first request is https? If it is, are you being redirected to http before being redirected to google? (You will have to watch your request log in your browser to check).

**Comment by moreiramarti** [comment]
I'm pretty sure but I'm doing ssl offloading through haproxy maybe the issue comes from that.

**Comment by thomseddon** [comment]
Yep, that will be the issue - the way this tool works at the moment is to look at the protocol of the request as received by traefik.

I could look at a way to override this in the future but unfortunately this wouldn't be a quick fix for me

**Comment by moreiramarti** [comment]
Ok I understand
Thanks you for tour help

Le mer. 6 févr. 2019 à 18:07, Thom Seddon <notifications@github.com> a
écrit :
