### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by rxbn** [thomseddon/traefik-forward-auth#276]
Hi everyone :)

First: thanks a lot for this amazing tool!

I just wanted to know whether traefik-forward-auth is still actively maintained... it seems as if there are no new commits or releases.

I have an issue when logging in using Safari:
Sometimes upon login, I get a "Not authorized" error that remedies itself after going back to the page I wanted to visit. I have seen some issues about this exact problem, but I can't seem to find any of them.

Thanks a lot in advance!

Best,
Robin

**Comment by kubrickfr** [comment]
Did you ever get an answer?

Or is it tgat this project has quietly been moved to traefik enterprise and the open source version left to die?

**Comment by rxbn** [comment]
@kubrickfr unfortunately not, I have since switched to nginx and oauth2-proxy.
