### ISSUE TITLE
Forwarded Ip is ignored

### ISSUE THREAD

**Issue by StiviiK** [thomseddon/traefik-forward-auth#29]
If Traefik is configured as LB and with `externalTrafficPolicy: Local`, the Ip address logged (and i guess used for verification) is a internal cluster ip, instead of the real client ip.

```
time="2019-02-20T17:29:52Z" level=warning msg="Error validating csrf cookie: Invalid CSRF state value" RemoteAddr="10.244.0.237:58794" csrf=ASDF state=
time="2019-02-20T17:30:45Z" level=error msg="Invalid cookie: Invalid cookie mac" RemoteAddr="10.244.0.237:58794"
```

**Comment by thomseddon** [comment]
The "RemoteAddr" is read directly from the request, so this would be the expected behaviour: https://github.com/thomseddon/traefik-forward-auth/blob/master/main.go#L23

Perhaps this could be improved in this scenario!

I want to test this with kubernetes a bit more, so this would be one to look at whilst that's being done.

**Comment by chenrui333** [comment]
I can actually use `docker-compose-dev.yml` to reproduce this issue.

0. create OAuth API, configure `http://localhost:8085/_oauth`
1. update the `traefik-forward-auth` env setup
2. `docker-compose -f docker-compose-dev.yml up`
3. update virtual host and access `http://localhost:8085`

I can always see 
```
traefik-forward-auth_1  | time="2019-04-16T03:27:53Z" level=error msg="Invalid cookie: Invalid cookie mac" RemoteAddr="172.19.0.3:47630"
```

**Comment by chenrui333** [comment]
http request would be like below:
```
Cookie: _ga=GA1.1.1551400415.1547069710; _forward_auth=05Kj15XruH2T1MNGSDJ62KCfujj3is2WnGaLb5h2usM=|1555425295|rchen@meetup.com
Host: whoami.localhost.com
```

**Comment by chenrui333** [comment]
I turned on the DEBUG log:
```
traefik_1               | time="2019-04-16T03:45:22Z" level=debug msg="Creating server server-example-whoami2-1-d0bbe061a5e0438aae1a72e9084b9114 at http://172.19.0.2:80 with weight 1"
traefik_1               | time="2019-04-16T03:45:22Z" level=debug msg="Creating route route-frontend-Host-whoami-localhost-org-1 Host:whoami.localhost.org"
traefik_1               | time="2019-04-16T03:45:22Z" level=info msg="Server configuration reloaded on :80"
traefik_1               | time="2019-04-16T03:45:22Z" level=info msg="Server configuration reloaded on :8080"
traefik-forward-auth_1  | time="2019-04-16T03:45:33Z" level=error msg="Invalid cookie: Invalid cookie mac" RemoteAddr="172.19.0.5:50662"
traefik_1               | time="2019-04-16T03:45:33Z" level=debug msg="Remote error http://traefik-forward-auth:4181. StatusCode: 401"
```

**Comment by chenrui333** [comment]
Now I comment out the lines:
```
    # [entryPoints.http.auth.forward]
    # address = "http://traefik-forward-auth:4181"
    # authResponseHeaders = ["X-Forwarded-User"]
```

Seems working for my favor now.

**Comment by thomseddon** [comment]
I've just pushed a commit that should fix this: https://github.com/thomseddon/traefik-forward-auth/commit/f1ba9b5ac49abac977651552193b3ea87166b423

I will tag and release this next week :)

**Comment by thomseddon** [comment]
This is included in v2 which has been released today
