### ISSUE TITLE
Keycloak Authorization

### ISSUE THREAD

**Issue by gcaracuel** [thomseddon/traefik-forward-auth#309]
I have tested successfully authentication flow but need to go deeper and implement Authorization and looks like this tool is not supporting this flow, I am right?

**Comment by chenrui333** [comment]
Why does it get closed?

**Comment by gcaracuel** [comment]
Not actually a problem. Keycloak authorization is not even a thing yet, almost no service does implement this but it rely on clients to implement authorization I am afraid is a bit out of the scope of this project.
