### ISSUE TITLE
invalid node rule: string

### ISSUE THREAD

**Issue by Molnfront** [thomseddon/traefik-forward-auth#315]
I'm trying to use rules, but it won't work, not even the simplest rule.

I get: level=error msg="invalid node rule: string"

This is how I want it to be:

```
  labels:
      - traefik.enable=true 
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_ui.rule.action=allow
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_ui.rule=Host(`${HOST}`)
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_ui.rule.action=auth"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_ui.rule=Host(`${HOST}`)&&Path(`/wallet`)"
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_ui.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_ui.tls.certresolver=letsencrypt
      - traefik.frontend.auth.forward.trustForwardHeader=true    
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_ui.middlewares=traefik-forward-auth 
```      

If I remove action I get no error

I have also tried with rule.one.rule and rule.two.rule to separate each rule. But same error.

**Comment by Molnfront** [comment]
Ok, giving up! 

It's a good solution for simple use cases, when you need to protect a whole server. 

But when rule and action is only theoretically working it's not possible to use in a more flexible scenario.

It would have helped with more advanced yml examples such as one with a working rule.action.

I have probably tried every possible combination even use rule in the command option:

´´´
command:
      - "--traefik.http.routers.${COMPOSE_PROJECT_NAME}_ui.rule.one.action=auth"
      - "--traefik.http.routers.${COMPOSE_PROJECT_NAME}_ui.rule.one.rule=Host(`${HOST}`)&&Path(`/8bywc3`)"  
  ´´´

**Comment by chelming** [comment]
see #321. you can do it as a file and mount the file.

**Comment by chelming** [comment]
It'd probably work with the `command` option, but you're passing in what looks like a label. you could try something like:
```yaml
command:
  - "rule.one.action=allow"
  - "rule.one.rule=Host(`${HOST}`)&&Path(`/8bywc3`)"
```

**Comment by chelming** [comment]
Throwing in a note that you might also want to use `PathPrefix` instead of path since path appears to require it to be _exact_ with no additional paths or params.

**Comment by Molnfront** [comment]
Ok thanks! Will give it a try when I got the time..
