### ISSUE TITLE
Publish 0.1.0 to docker hub

### ISSUE THREAD

**Issue by drubin** [thomseddon/traefik-forward-auth#32]
Currently, there are only 2 tags `dev` and `latest` it would be great if you published the `0.1.0` as a tag which is immutable 

https://hub.docker.com/r/lslio/traefik-forward-auth/tags
https://github.com/thomseddon/traefik-forward-auth/releases

Also is it possible to make use of dockerhub's automated builds so they are verifiable?

Thanks for this! It's a simple approach in the absence of traefik middleware.

**Comment by thomseddon** [comment]
Great point! I had been meaning to do this with the upcoming v2 release, I've been building all the backwards comparability but the sooner people can start using the tagged v1 release the better.

I've just added a "1" docker tag: https://hub.docker.com/r/thomseddon/traefik-forward-auth/tags

**Comment by drubin** [comment]
@thomseddon thanks for the update any chance we can get the tags pushed `0.1.0` so they match? I think docker-hub has an automatic integration that builds tags/releases on github v1 and v2?

**Comment by thomseddon** [comment]
So they match what?

**Comment by thomseddon** [comment]
Ah sorry, I have just seen I published a git tag with 0.1.0!! I had forgotten about this, I will update the builds tomorrow

**Comment by thomseddon** [comment]
I've just published a 0.1.1 tag based on the latest code which docker hub has dutifully built :)

**Comment by drubin** [comment]
Thanks very much!
