### ISSUE TITLE
Timeouts?

### ISSUE THREAD

**Issue by mdbraber** [thomseddon/traefik-forward-auth#46]
Hi,

I've set up traefik-forward-auth (from @funkypenguin's patch). It works great, but in some case I get timeouts where I can't access the hosts behind the Traefik controller. I'm thinking the bottleneck is traefik-forward-auth which is not able to process the request in time? I can't find any logs though that help me diagnose where the problem is. Anyone else experienced timeout or slowness using traefik-forward-auth?

**Comment by thomseddon** [comment]
Are you seeing a log when the request is received?

What provider are you using?

**Comment by mdbraber** [comment]
@thomseddon thanks for taking the time to respond! No I'm not seeing no request in the logs at the moment it's timing out. At the same time (doing a simultaneous ping) the host is still reachable, so from the first idea it won't seem like core network issues.

If I'm correct a request to a Traefik backend with traefik-forward-auth follows the following path (presuming a valid cookie is set already). My traefik-forward-auth container name is 'auth-trusted'.

1) connect to Traefik IP with SNI target.example.com
2) redirect to internal traefik.frontend.auth.forward.address=http://auth-trusted:4181
3) validate the cookie and redirect to Traefik IP with SNI target example.com
4) Traefik redirects the request to the hostname:port defined for target.example.com

Is that correct? I'm trying to see where in this path there might be something going wrong...

**Comment by mdbraber** [comment]
This can be closed - the source of the problem was assymetric routing causing packets not to arrive at the right destination.

**Comment by shaggykp** [comment]
Hi,

I have Traefik configured behind MetalLB and I'm experiencing timeouts as well on my HTTP and TCP connections.  Would you mind going into more detail about how you determined that you were getting assymetric routing with packets not arriving at the intended destination?  Perhaps it may shed some light on the issue we are seeing.

Thanks in advance,
Kavita

**Comment by TheTechromancer** [comment]
Related:

- https://github.com/traefik/traefik/issues/9857
