### ISSUE TITLE
Getting infinite redirects

### ISSUE THREAD

**Issue by atmosx** [thomseddon/traefik-forward-auth#55]
I'm trying to setup oauth2 configuration in docker swarm with traefik + traefik-forward-auth. My `traefik-forward-auth:v2.0.0` configuration is:

```
client-id=<...>
client-secret=<...>
secret=<...>
cookie-domain=example.com
domain=example.com
auth-host=auth.example.com
log-level=debug
```

Service traefik labels configuration:

```
"traefik.enable": "true",
"traefik.frontend.auth.forward.address": "http://traefik_forward_auth:4181",
"traefik.frontend.auth.forward.authResponseHeaders": "X-Forwarded-User",
"traefik.frontend.auth.forward.trustForwardHeader": "true",
"traefik.frontend.entryPoints": "http,https",
"traefik.frontend.redirect.entryPoint": "https",
"traefik.frontend.rule": "Host: internal-website.example.com",
```

Debug logs from `traefik-forward-auth`:
```
traefik_forward_auth.1.8yhf0jqbh2k4@ip-10-0-12-160    | time="2019-06-26T04:46:23Z" level=debug msg="Set CSRF cookie and redirecting to google login" source_ip=10.255.0.9
traefik_forward_auth.1.8yhf0jqbh2k4@ip-10-0-12-160    | time="2019-06-26T04:46:23Z" level=debug msg=Done source_ip=10.255.0.9
traefik_forward_auth.2.qez8i8b3kxij@ip-10-0-10-223    | time="2019-06-26T04:46:24Z" level=debug msg="Authenticating request" headers="map[Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8] Accept-Encoding:[gzip, deflate, br] Accept-Language:[en-US,en;q=0.5] Cache-Control:[no-cache] Cookie:[_forward_auth_csrf=<cookie>] Pragma:[no-cache] Referer:[https://accounts.google.gr/accounts/SetSID] Te:[trailers] Upgrade-Insecure-Requests:[1] User-Agent:[Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0] X-Forwarded-For:[10.255.0.9] X-Forwarded-Host:[auth.example.com] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Forwarded-Server:[09caed4a73f2] X-Real-Ip:[10.255.0.9]]" rule=default source_ip=10.255.0.9
```

The google oauth2 uses the domain "auth.example.com/_oauth". 

1. Request to internal-website.example.com/
2. User redirected to Google login
3. After Google login, user is redirected to auth.example.com/_oauth

Up to this point it works, I'm able to authenticate to google and get redirected back to auth website.
But then instead of token and CSRF validation, I get redirect again to google and the auth process starts from (1).
I don't see logs of failed redirection or anything like that on the server (traefik-forward-auth) side, it is like a fresh start.

4. Token, user and CSRF cookie is validated, auth cookie is set to example.com
5. User is redirected to internal-website.example.com
6. Request is allowed

Is there anything obvious I'm missing?

**Comment by atmosx** [comment]
Following the advice found at https://geek-cookbook.funkypenguin.co.nz/ha-docker-swarm/traefik-forward-auth/ I added the following labels to the `traefik-forward-auth` container as well:

```
"traefik.frontend.auth.forward.address": "http://traefik_forward_auth:4181",
"traefik.frontend.auth.forward.authResponseHeaders": "X-Forwarded-User",
```

and it worked!

**Comment by gregfr** [comment]
I have the same problem, where you able to have it working with Traefik 2?

**Comment by denysvitali** [comment]
@gregfr / @atmosx , try my branch: https://github.com/thomseddon/traefik-forward-auth/pull/78, specifically this commit: https://github.com/thomseddon/traefik-forward-auth/pull/78/commits/da35933d58d45a4d6d4917682f4e42395eda2fc7
