### ISSUE TITLE
[Request] Example website / end result

### ISSUE THREAD

**Issue by Poltergeisen** [thomseddon/traefik-forward-auth#61]
Would it be possible to host this externally to show an example of what the landing page might look like?

**Comment by robertbaker** [comment]
There is no landing page. You just get redirected to the Google Account Choose Screen or The Google Login screen, then once you choose your google account / login, then it redirects to whatever container your using

**Comment by ageisen2000** [comment]
Thanks for the answer! I'll close this.

**Comment by Poltergeisen** [comment]
Thanks for the answer! I wasn't sure if that was the case or not. Closing this issue.
