### ISSUE TITLE
No prompt for user login unless logged out of Google account

### ISSUE THREAD

**Issue by ahmedmagdiosman** [thomseddon/traefik-forward-auth#64]
If I'm logged in using a different non-whitelisted account using Chrome browser, I get a  "Not Authorized" without prompting me to login with the other authorized account.  On the other side, if I'm using Chrome with the whitelisted account logged in, I don't get the login consent and get authorized automatically.

Is there an config to force account selection?

 It should be possible with: ``prompt=select_account``

I just can't figure out where I can change this.

**Comment by tdorsey** [comment]
set the environment variable PROVIDERS_GOOGLE_PROMPT=select_account

**Comment by ahmedmagdiosman** [comment]
Thanks a lot! I don't know how I missed it. It's right there in the README.
