### ISSUE TITLE
Rules on the same domain as the auth domain break the redirect

### ISSUE THREAD

**Issue by SuperSandro2000** [thomseddon/traefik-forward-auth#72]
When I add this rule ``--rules.auth.action=allow --rules.auth.rule="Host(`auth.domain.com`)"`` to allow my auth domain the redirect back to the service breaks and traefik gets stuck on ``auth.domain.com``.

**Comment by thomseddon** [comment]
Why do you want to do this?

Auth host style redirects should work without this if that's what you're try to achieve :)

**Comment by SuperSandro2000** [comment]
Cause I set ``DEFAULT_ACTION=auth`` and I thought that it otherwise wants to authenticate the auth domain.

We should probably add this to the readme.

**Comment by thomseddon** [comment]
Just to circle back on this, you don't need to add an explicit allow rule for your auth domain. As you have observed, this will actually break your setup (as this will be applied prior to the auth endpoints so will actually prevent authentication from completed).

Please re-open this issue if you're still having issues!
