### ISSUE TITLE
README examples for Traefik 2

### ISSUE THREAD

**Issue by cry** [thomseddon/traefik-forward-auth#74]
Traefik 2 has finally left beta and is now in general availability! It's probably worth it to add examples on how to use this with Traefik 2 into the README, as its not entirely obvious how to migrate to v2. 

I have examples on my blog that I'd be happy to copy paste across if they're actually correct: https://carey.li/2019/10/01/traefik-2-sso-ssl/.

**Comment by SuperSandro2000** [comment]
Things I like to be changed before this could happen:

Don't mount ``/var/run/docker.sock`` into the traefik container. Use a proxy like https://github.com/Tecnativa/docker-socket-proxy.

Do not set the api to insecure. Use `` traefik.http.routers.traefik.service=api@internal``.

It is not SSO. I still wouldn't be signed into Gitea or something. It is proxy authentication or something similar.

Log level shouldn't be debug in production.

Whitelist should work like:
``whitelist = hello@carey.li,another.carey.li``

Google provider probably break with the next update.
````
providers.google.client-id = google-client-id
providers.google.client-secret = google-client-secret
````

Also you did not show how to get those creds as this can be quite hard if you never done it before.

**Comment by thomseddon** [comment]
I'll have to do some reading to comment on this, happy for any other reviewer to add their comment in the meatime

**Comment by thomseddon** [comment]
I've updated the README (8902cf8) and added a lot of new examples for traefik recently, happy to say this is now resolved!
