### ISSUE TITLE
Customize whitelist/domain for specific services/endpoints

### ISSUE THREAD

**Issue by rubasace** [thomseddon/traefik-forward-auth#76]
Is it currently possible to override the whitelist/domain for a particular service?

I have a server based on docker-compose with 35 services. Some of them I want them to be accessible but more people than me while the most part of them I would like them to keep private. Is there anything I can customize via labels or similar for such a case?

If not, is it possible to disable the OAuth2 on certain endpoints?

**Comment by thomseddon** [comment]
It's not currently possible to set different whitelists, but this is certainly something we could support via the new `rules` config!

I actually quite like the idea of making this and a few other variables editable under `rules` so I'll leave this issue open :)

In the meantime, you can disable OAuth2 with something like:

```
rule.1.action = allow
rule.1.rule = Path(`/public`)
```

See `rule` under: https://github.com/thomseddon/traefik-forward-auth#option-details

**Comment by Webunity** [comment]
@thomseddon isn't this a dupe of my issue #57 ?

**Comment by rubasace** [comment]
@Webunity agree :)
