### ISSUE TITLE
Read ip from X-Forwarded-For header

### ISSUE THREAD

**Issue by SuperSandro2000** [thomseddon/traefik-forward-auth#97]
Right now the source ip in the log shows an internal Docker ip and I want to change it to the real ip of the client.
Traefik set the F-Forwarded-For and X-Real-Ip Header with this information.
Could this be added?

**Comment by thomseddon** [comment]
Hmm, I actually fixed this a while ago as I had the same problem, it's now read from X-Forwarded-For: https://github.com/thomseddon/traefik-forward-auth/blob/master/internal/server.go#L196

Are you running docker swarm or k8s and could you check what container the logged address is assigned too?

**Comment by SuperSandro2000** [comment]
I think I know why it did not work before on my machine. I had the userland proxy still enabled and for internal traffic the ip was correct but for outside traffic it got the container ip. I am not sure if this should be mention somewhere in the readme.
